In [ ]:
#A total of 15 print-heads were randomly selected and tested until failure.
#The durability of each print-head (in millions of characters) was recorded as follows:
1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.20, 1.33, 1.18, 1.22, 1.29

#a. Build 99% Confidence Interval Using Sample Standard Deviation
#b. Build 99% Confidence Interval Using Known Population Standard Deviation. Population standard deviation is 0.2.
#we know the formulas for confidence interval for known as well as unknown population standard deviation(sigma)


#for known sigma, confidence interval = sample mean   -+  z(1-alpha)*sigma/sqrt(n)   where,
#z(1-alpha)    :   z distribution of confidence level
#   n          :  length of sample data


#For unknown sigma :  sample mean -+ t(1-alpha,n-1)* s/sqrt(n)      where,
#t(1-alpha,n-1)    :  t distribution of confidence interval for degree of freedom (n-1)
#     n            :  length of sample data
#     s            :  sample standard deviation
#     t            :  t-distribution ofconfidence interval




In [1]:


from scipy import stats
import pandas as pd
import numpy as np


In [5]:
durability=[1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.20, 1.33, 1.18, 1.22, 1.29]               #given sample data

In [6]:
len(durability)

15

In [17]:
#To apply mean() and std() functions we will create dataframe of list.
durability_data=pd.DataFrame(durability,columns=["Durability of print-head"])
durability_data

Durability of print-head
0                       1.13
1                       1.55
2                       1.43
3                       0.92
4                       1.25
5                       1.36
6                       1.32
7                       0.85
8                       1.07
9                       1.48
10                      1.20
11                      1.33
12                      1.18
13                      1.22
14                      1.29

In [20]:
durability_data.mean()

Durability of print-head    1.238667
dtype: float64

In [21]:
durability_data.std()

Durability of print-head    0.193164
dtype: float64

In [26]:
np.sqrt(len(durability_data))

3.872983346207417

In [34]:
#a)To calculate confidence interval, if we don't know sigma value. weuse following steps
confidence_interval_t =stats.t.interval(0.99,14,durability_data.mean(),durability_data.std())
print(confidence_interval_t)
print("The confidence interval for 99% durability of print-head","\n",np.round(confidence_interval_t,4))

(array([0.66364743]), array([1.8136859]))
The confidence interval for 99% durability of print-head 
 [[0.6636]
 [1.8137]]


In [27]:
#b)To calculate confidence interval,if we know the sigma value. we use below function
confidence_interval_z = stats.norm.interval(0.99,durability_data.mean(),durability_data.std())
print(confidence_interval_z)
print("The confidence interval of 99% durability of  print-head is : \n ",np.round(confidence_interval_z,4), end=" ")

(array([0.74110884]), array([1.73622449]))
The confidence interval of durability of  print-head is : 
  [[0.7411]
 [1.7362]] 

In [ ]:
#a)for unknown sigma : Confidence Interval for 99% is : 0.6636 to 1.8137

#    Here, we have norm.interval and no need of degree of freedom that is n-1. soonly 3 attributes needed.
#          Internally z-distribution value is used from z-distribution table


#b)for known sigma   : Confidence Interval for 99% is : 0.7411 to 1.7362

#    Here, we have t.interval and degreeoffreedom n-1 is used so the attributes are of 4.
#           Internally, t-distribution value is calculated using formula, (sample mean-population mean)/(samplestandard deviation/sqrt(n)
#           and         sample standard deviation =sqrt(1/(n-1)*summation(xi-sample mean)^2)